import React, { useEffect, useState } from 'react'
import { useRouter } from 'next/router'
import Head from 'next/head'
import DefaultLayout from '../../layout/Default'
import Navbar from '../../components/Navbar'

export default function EachCat() {
    const router = useRouter()
    const { id } = router.query;
    const [cat, setCat] = useState()

    const dataFetch = async () => {
        const res = await fetch(`/api/cats/${id}`)
        const data = await res.json();
        setCat(data)
    }

    useEffect(() => {
        dataFetch();
    }, []);

    console.log(cat);

    return (
        <div>
            <div>
                <Head>
                    <title>{id}</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Navbar/>
                <div className='container mt-5'>
                    <button onClick={()=> {
                        router.push('/cats')
                    }} className='btn btn-primary'> back to menu</button>
                    <DefaultLayout>
                        {cat && (
                            <div className="container mt-5" style={{ display: "flex" }}>
                                <img src={cat.image.url} />
                                <div className="mx-5">
                                    <h1>{cat.name}</h1>
                                    <p>{cat.description} </p>
                                </div>
                            </div>
                        )}
                    </DefaultLayout>
                </div>


            </div>
        </div>
    )
}
