import Head from 'next/head'
import Navbar from '../components/Navbar'
import MainView from '../components/mainView/mainView'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Asliddin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Navbar/>
        <div  className='container mt-5'>
        <MainView/>
        </div>
    </div>
  )
}
